# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-26 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20180503_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='id_banner',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u8f6e\u64ad'),
        ),
    ]
