# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-26 14:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_course_id_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='id_banner',
            new_name='is_banner',
        ),
    ]
