# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-04 16:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180404_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='nike_name',
            new_name='nick_name',
        ),
    ]
